In [5]:
import numpy as np
li = [1,2,3,4,5,6,7,8]
type(li)

list

In [7]:
x = np.array(li)

In [8]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
type(x)

numpy.ndarray

In [10]:
import pandas as pd
import numpy as np
data1 = np.array([1,None, 2,3])
data1

array([1, None, 2, 3], dtype=object)

In [11]:
pd.Series([1,np.nan,2,None])


0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [24]:
x = pd.Series(range(3), dtype=int)
x

0    0
1    1
2    2
dtype: int32

In [13]:
x[0]

0

In [14]:
x[0] = None

In [15]:
x

0    NaN
1    1.0
dtype: float64

In [ ]:
import pandas as pd
import numpy as np


In [16]:
data1=np.array([1, None,2,3])
data1


array([1, None, 2, 3], dtype=object)

In [17]:
%timeit np.arange(1E6, dtype=int).sum()

3.12 ms ± 233 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
%timeit np.arange(1E6, dtype=object).sum()

105 ms ± 4.91 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [19]:
data2= np.array([1,np.nan,3,4])
data2

array([ 1., nan,  3.,  4.])

In [20]:
type(data2)

numpy.ndarray

In [21]:
1 + np.nan

nan

In [22]:
1 * np.nan

nan

In [23]:
0 * np.nan

nan

In [26]:
import pandas as pd

import numpy as np
pd.Series([1,np.nan,2,None,pd.NA])

0       1
1     NaN
2       2
3    None
4    <NA>
dtype: object

In [27]:
data=pd.Series([1,np.nan,'hello',None])
data


0        1
1      NaN
2    hello
3     None
dtype: object

In [28]:
data.fillna(0)

0        1
1        0
2    hello
3        0
dtype: object

In [50]:
df = pd.read_csv('COVID19Cases.csv')
df

C:\Users\trkro\AppData\Local\Temp\ipykernel_11720\4263181853.py:1: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('COVID19Cases.csv')


Case_Type  People_Total_Tested_Count  Cases  Difference       Date  \
0       Confirmed                        NaN      6           0  5/22/2020   
1       Confirmed                        NaN      0           0   2/3/2020   
2          Deaths                        NaN      0           0   3/1/2020   
3       Confirmed                        NaN     23           0  4/21/2020   
4          Deaths                        NaN     56           0  5/11/2020   
...           ...                        ...    ...         ...        ...   
950665     Deaths                        NaN      0           0  1/22/2020   
950666  Confirmed                        NaN      0           0  1/22/2020   
950667     Deaths                        NaN      0           0  1/22/2020   
950668  Confirmed                        NaN      0           0  1/22/2020   
950669  Confirmed                        NaN      0           0  1/22/2020   

                     Combined_Key       Country_Region Province_State  \
0                  Western Sahara       Western Sahara            NaN   
1                     Switzerland          Switzerland            NaN   
2                          Cyprus               Cyprus            NaN   
3             Antigua and Barbuda  Antigua and Barbuda            NaN   
4                        Thailand             Thailand            NaN   
...                           ...                  ...            ...   
950665      Missoula, Montana, US                   US        Montana   
950666    Ontonagon, Michigan, US                   US       Michigan   
950667  Sargent, North Dakota, US                   US   North Dakota   
950668         Ohio, Kentucky, US                   US       Kentucky   
950669    Marion, Mississippi, US                   US    Mississippi   

           Admin2 iso2 iso3     FIPS        Lat        Long  Population_Count  \
0             NaN   EH  ESH      NaN  24.215500  -12.885800          597330.0   
1             NaN   CH  CHE      NaN  46.818200    8.227500         8654618.0   
2             NaN   CY  CYP      NaN  35.126400   33.429900         1207361.0   
3             NaN   AG  ATG      NaN  17.060800  -61.796400           97928.0   
4             NaN   TH  THA      NaN  15.870032  100.992541        69799978.0   
...           ...  ...  ...      ...        ...         ...               ...   
950665   Missoula   US  USA  30063.0  47.037286 -113.921351          119600.0   
950666  Ontonagon   US  USA  26131.0  46.665226  -89.313905            5720.0   
950667    Sargent   US  USA  38081.0  46.108304  -97.632172            3898.0   
950668       Ohio   US  USA  21183.0  37.477518  -86.853681           23994.0   
950669     Marion   US  USA  28091.0  31.231326  -89.820922           24573.0   

        People_Hospitalized_Cumulative_Count  \
0                                        NaN   
1                                        NaN   
2                                        NaN   
3                                        NaN   
4                                        NaN   
...                                      ...   
950665                                   NaN   
950666                                   NaN   
950667                                   NaN   
950668                                   NaN   
950669                                   NaN   

                                              Data_Source  \
0       2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...   
1       2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...   
2       2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...   
3       2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...   
4       2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...   
...                                                   ...   
950665  2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...   
950666  2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...   
950667  2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...   
950668  2019 Novel Coronavirus COV

In [51]:
df.head(5)

Case_Type  People_Total_Tested_Count  Cases  Difference       Date  \
0  Confirmed                        NaN      6           0  5/22/2020   
1  Confirmed                        NaN      0           0   2/3/2020   
2     Deaths                        NaN      0           0   3/1/2020   
3  Confirmed                        NaN     23           0  4/21/2020   
4     Deaths                        NaN     56           0  5/11/2020   

          Combined_Key       Country_Region Province_State Admin2 iso2 iso3  \
0       Western Sahara       Western Sahara            NaN    NaN   EH  ESH   
1          Switzerland          Switzerland            NaN    NaN   CH  CHE   
2               Cyprus               Cyprus            NaN    NaN   CY  CYP   
3  Antigua and Barbuda  Antigua and Barbuda            NaN    NaN   AG  ATG   
4             Thailand             Thailand            NaN    NaN   TH  THA   

   FIPS        Lat        Long  Population_Count  \
0   NaN  24.215500  -12.885800          597330.0   
1   NaN  46.818200    8.227500         8654618.0   
2   NaN  35.126400   33.429900         1207361.0   
3   NaN  17.060800  -61.796400           97928.0   
4   NaN  15.870032  100.992541        69799978.0   

   People_Hospitalized_Cumulative_Count  \
0                                   NaN   
1                                   NaN   
2                                   NaN   
3                                   NaN   
4                                   NaN   

                                         Data_Source     Prep_Flow_Runtime  
0  2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...  6/4/2020 11:15:39 PM  
1  2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...  6/4/2020 11:15:39 PM  
2  2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...  6/4/2020 11:15:39 PM  
3  2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...  6/4/2020 11:15:39 PM  
4  2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...  6/4/2020 11:15:39 PM

In [52]:
df.tail(5)

Case_Type  People_Total_Tested_Count  Cases  Difference       Date  \
950665     Deaths                        NaN      0           0  1/22/2020   
950666  Confirmed                        NaN      0           0  1/22/2020   
950667     Deaths                        NaN      0           0  1/22/2020   
950668  Confirmed                        NaN      0           0  1/22/2020   
950669  Confirmed                        NaN      0           0  1/22/2020   

                     Combined_Key Country_Region Province_State     Admin2  \
950665      Missoula, Montana, US             US        Montana   Missoula   
950666    Ontonagon, Michigan, US             US       Michigan  Ontonagon   
950667  Sargent, North Dakota, US             US   North Dakota    Sargent   
950668         Ohio, Kentucky, US             US       Kentucky       Ohio   
950669    Marion, Mississippi, US             US    Mississippi     Marion   

       iso2 iso3     FIPS        Lat        Long  Population_Count  \
950665   US  USA  30063.0  47.037286 -113.921351          119600.0   
950666   US  USA  26131.0  46.665226  -89.313905            5720.0   
950667   US  USA  38081.0  46.108304  -97.632172            3898.0   
950668   US  USA  21183.0  37.477518  -86.853681           23994.0   
950669   US  USA  28091.0  31.231326  -89.820922           24573.0   

        People_Hospitalized_Cumulative_Count  \
950665                                   NaN   
950666                                   NaN   
950667                                   NaN   
950668                                   NaN   
950669                                   NaN   

                                              Data_Source  \
950665  2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...   
950666  2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...   
950667  2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...   
950668  2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...   
950669  2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...   

           Prep_Flow_Runtime  
950665  6/4/2020 11:15:39 PM  
950666  6/4/2020 11:15:39 PM  
950667  6/4/2020 11:15:39 PM  
950668  6/4/2020 11:15:39 PM  
950669  6/4/2020 11:15:39 PM

In [53]:
df.columns

Index(['Case_Type', 'People_Total_Tested_Count', 'Cases', 'Difference', 'Date',
       'Combined_Key', 'Country_Region', 'Province_State', 'Admin2', 'iso2',
       'iso3', 'FIPS', 'Lat', 'Long', 'Population_Count',
       'People_Hospitalized_Cumulative_Count', 'Data_Source',
       'Prep_Flow_Runtime'],
      dtype='object')

In [61]:
df.People_Total_Tested_Count

0         True
1         True
2         True
3         True
4         True
          ... 
950665    True
950666    True
950667    True
950668    True
950669    True
Name: People_Total_Tested_Count, Length: 950670, dtype: bool

In [62]:
df.People_Total_Tested_Count.isnull()

0         True
1         True
2         True
3         True
4         True
          ... 
950665    True
950666    True
950667    True
950668    True
950669    True
Name: People_Total_Tested_Count, Length: 950670, dtype: bool

In [63]:
df.People_Total_Tested_Count.isnull().sum()

944622

In [64]:
df.People_Hospitalized_Cumulative_Count

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
950665   NaN
950666   NaN
950667   NaN
950668   NaN
950669   NaN
Name: People_Hospitalized_Cumulative_Count, Length: 950670, dtype: float64

In [65]:
df.People_Hospitalized_Cumulative_Count.isnull()

0         True
1         True
2         True
3         True
4         True
          ... 
950665    True
950666    True
950667    True
950668    True
950669    True
Name: People_Hospitalized_Cumulative_Count, Length: 950670, dtype: bool

In [66]:
df.People_Hospitalized_Cumulative_Count.isnull().sum()

944622

In [67]:
df.Province_State.isnull()

0          True
1          True
2          True
3          True
4          True
          ...  
950665    False
950666    False
950667    False
950668    False
950669    False
Name: Province_State, Length: 950670, dtype: bool

In [68]:
df.Province_State.isnull().sum()

49410

In [69]:
df.People_Total_Tested_Count

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
950665   NaN
950666   NaN
950667   NaN
950668   NaN
950669   NaN
Name: People_Total_Tested_Count, Length: 950670, dtype: float64

In [70]:
df.People_Total_Tested_Count.notnull()

0         False
1         False
2         False
3         False
4         False
          ...  
950665    False
950666    False
950667    False
950668    False
950669    False
Name: People_Total_Tested_Count, Length: 950670, dtype: bool

In [71]:
data[df.People_Total_Tested_Count.notnull()]

Series([], dtype: object)

In [ ]:
data[data.notnull()]

In [74]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [72]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [77]:
data1 = df.People_Total_Tested_Count.dropna()
data1

67173     151810.0
67256       2873.0
67499     959071.0
67509     581944.0
67567      17850.0
            ...   
949461    103768.0
949484    105326.0
949566     80896.0
949648    422904.0
949751     30596.0
Name: People_Total_Tested_Count, Length: 6048, dtype: float64

In [79]:
data1 = df.People_Total_Tested_Count.dropna().sum()
data1

1011828034.0

In [80]:
data1 = df.People_Total_Tested_Count.dropna().count()
data1

6048

In [81]:
data2 = df.People_Total_Tested_Count.fillna(0)
data2


0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ... 
950665    0.0
950666    0.0
950667    0.0
950668    0.0
950669    0.0
Name: People_Total_Tested_Count, Length: 950670, dtype: float64

TypeError: Series.count() takes 1 positional argument but 2 were given